# Generated by Django 3.2.14 on 2022-07-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0001_initial'),
    ]

    # No real DB changes
    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
